-- Comments can be written prior to the start of the program if
--  you desire, or nearly anywhere within a program.

procedure Comments is    -- Comments can start anywhere on the line
                         -- but they end at the end of the line.
begin

   Put("This program illustrates the use ");  -- Text output
   Put("of comments.");                       -- More text output
                                              -- Blank program line
   New_Line;                                  -- CR/LF to monitor

-- Put("This is not an output statement, it is a comment.");

end Comments;
-- Comments can even
        -- be written after the
                 -- program is complete.




-- Result of execution

-- This program illustrates the use of comments.

